export const conditionOperators = {
  // String
  StringEquals: { description: 'Exact matching, case sensitive' },
  StringEqualsIfExists: { description: 'Exact matching, case sensitive; true if key is absent' },
  'ForAllValues:StringEquals': { description: 'All values must match at least one policy value (case sensitive)' },
  'ForAnyValue:StringEquals': { description: 'At least one value must match a policy value (case sensitive)' },
  StringNotEquals: { description: 'Negated matching, case sensitive' },
  StringNotEqualsIfExists: { description: 'Negated matching, case sensitive; true if key is absent' },
  'ForAllValues:StringNotEquals': { description: 'None of the values can match any policy value (case sensitive)' },
  'ForAnyValue:StringNotEquals': { description: 'At least one value must not match any policy value (case sensitive)' },
  StringEqualsIgnoreCase: { description: 'Exact matching, ignoring case' },
  StringEqualsIgnoreCaseIfExists: { description: 'Exact matching, ignoring case; true if key is absent' },
  'ForAllValues:StringEqualsIgnoreCase': {
    description: 'All values must match at least one policy value (case insensitive)',
  },
  'ForAnyValue:StringEqualsIgnoreCase': {
    description: 'At least one value must match a policy value (case insensitive)',
  },
  StringNotEqualsIgnoreCase: { description: 'Negated matching, ignoring case' },
  StringNotEqualsIgnoreCaseIfExists: { description: 'Negated matching, ignoring case; true if key is absent' },
  'ForAllValues:StringNotEqualsIgnoreCase': {
    description: 'None of the values can match any policy value (case insensitive)',
  },
  'ForAnyValue:StringNotEqualsIgnoreCase': {
    description: 'At least one value must not match any policy value (case insensitive)',
  },
  StringLike: { description: 'Case-sensitive matching with wildcard support (* and ?)' },
  StringLikeIfExists: { description: 'Wildcard matching; true if key is absent' },
  'ForAllValues:StringLike': { description: 'All values must match at least one policy value pattern' },
  'ForAnyValue:StringLike': { description: 'At least one value must match a policy value pattern' },
  StringNotLike: { description: 'Negated case-sensitive matching with wildcard support' },
  StringNotLikeIfExists: { description: 'Negated wildcard matching; true if key is absent' },
  'ForAllValues:StringNotLike': { description: 'None of the values can match any policy value pattern' },
  'ForAnyValue:StringNotLike': { description: 'At least one value must not match any policy value pattern' },

  // Numeric
  NumericEquals: { description: 'Exact numeric matching' },
  NumericEqualsIfExists: { description: 'Exact numeric matching; true if key is absent' },
  'ForAllValues:NumericEquals': { description: 'All values must match at least one policy numeric value' },
  'ForAnyValue:NumericEquals': { description: 'At least one value must match a policy numeric value' },
  NumericNotEquals: { description: 'Negated numeric matching' },
  NumericNotEqualsIfExists: { description: 'Negated numeric matching; true if key is absent' },
  'ForAllValues:NumericNotEquals': { description: 'None of the values can match any policy numeric value' },
  'ForAnyValue:NumericNotEquals': { description: 'At least one value must not match any policy numeric value' },
  NumericLessThan: { description: 'Less than matching' },
  NumericLessThanIfExists: { description: 'Less than matching; true if key is absent' },
  'ForAllValues:NumericLessThan': { description: 'All values must be less than the policy value' },
  'ForAnyValue:NumericLessThan': { description: 'At least one value must be less than the policy value' },
  NumericLessThanEquals: { description: 'Less than or equals matching' },
  NumericLessThanEqualsIfExists: { description: 'Less than or equals matching; true if key is absent' },
  'ForAllValues:NumericLessThanEquals': { description: 'All values must be less than or equal to the policy value' },
  'ForAnyValue:NumericLessThanEquals': {
    description: 'At least one value must be less than or equal to the policy value',
  },
  NumericGreaterThan: { description: 'Greater than matching' },
  NumericGreaterThanIfExists: { description: 'Greater than matching; true if key is absent' },
  'ForAllValues:NumericGreaterThan': { description: 'All values must be greater than the policy value' },
  'ForAnyValue:NumericGreaterThan': { description: 'At least one value must be greater than the policy value' },
  NumericGreaterThanEquals: { description: 'Greater than or equals matching' },
  NumericGreaterThanEqualsIfExists: { description: 'Greater than or equals matching; true if key is absent' },
  'ForAllValues:NumericGreaterThanEquals': {
    description: 'All values must be greater than or equal to the policy value',
  },
  'ForAnyValue:NumericGreaterThanEquals': {
    description: 'At least one value must be greater than or equal to the policy value',
  },

  // Date
  DateEquals: { description: 'Matching a specific date' },
  DateEqualsIfExists: { description: 'Date matching; true if key is absent' },
  'ForAllValues:DateEquals': { description: 'All values must match a policy date value' },
  'ForAnyValue:DateEquals': { description: 'At least one value must match a policy date value' },
  DateNotEquals: { description: 'Negated date matching' },
  DateNotEqualsIfExists: { description: 'Negated date matching; true if key is absent' },
  'ForAllValues:DateNotEquals': { description: 'None of the values can match any policy date value' },
  'ForAnyValue:DateNotEquals': { description: 'At least one value must not match any policy date value' },
  DateLessThan: { description: 'Matching before a specific date and time' },
  DateLessThanIfExists: { description: 'Before date matching; true if key is absent' },
  'ForAllValues:DateLessThan': { description: 'All values must be before the policy date' },
  'ForAnyValue:DateLessThan': { description: 'At least one value must be before the policy date' },
  DateLessThanEquals: { description: 'Matching at or before a specific date and time' },
  DateLessThanEqualsIfExists: { description: 'At or before date matching; true if key is absent' },
  'ForAllValues:DateLessThanEquals': { description: 'All values must be at or before the policy date' },
  'ForAnyValue:DateLessThanEquals': { description: 'At least one value must be at or before the policy date' },
  DateGreaterThan: { description: 'Matching after a specific date and time' },
  DateGreaterThanIfExists: { description: 'After date matching; true if key is absent' },
  'ForAllValues:DateGreaterThan': { description: 'All values must be after the policy date' },
  'ForAnyValue:DateGreaterThan': { description: 'At least one value must be after the policy date' },
  DateGreaterThanEquals: { description: 'Matching at or after a specific date and time' },
  DateGreaterThanEqualsIfExists: { description: 'At or after date matching; true if key is absent' },
  'ForAllValues:DateGreaterThanEquals': { description: 'All values must be at or after the policy date' },
  'ForAnyValue:DateGreaterThanEquals': { description: 'At least one value must be at or after the policy date' },

  // Boolean
  Bool: { description: 'Boolean matching (true or false)' },
  BoolIfExists: { description: 'Boolean matching; true if key is absent' },
  'ForAllValues:Bool': { description: 'All values must match the policy boolean' },
  'ForAnyValue:Bool': { description: 'At least one value must match the policy boolean' },

  // Binary
  BinaryEquals: { description: 'Byte-for-byte comparison of base-64 encoded binary values' },
  BinaryEqualsIfExists: { description: 'Binary value matching; true if key is absent' },
  'ForAllValues:BinaryEquals': { description: 'All values must match a policy binary value' },
  'ForAnyValue:BinaryEquals': { description: 'At least one value must match a policy binary value' },

  // IP address
  IpAddress: { description: 'Matching a specific IP address or CIDR range' },
  IpAddressIfExists: { description: 'IP address matching; true if key is absent' },
  'ForAllValues:IpAddress': { description: 'All values must match a policy IP address or CIDR range' },
  'ForAnyValue:IpAddress': { description: 'At least one value must match a policy IP address or CIDR range' },
  NotIpAddress: { description: 'All IP addresses except the specified IP address or CIDR range' },
  NotIpAddressIfExists: { description: 'Negated IP address matching; true if key is absent' },
  'ForAllValues:NotIpAddress': { description: 'All values must not match any policy IP address or CIDR range' },
  'ForAnyValue:NotIpAddress': { description: 'At least one value must not match any policy IP address or CIDR range' },

  // ARN
  ArnEquals: { description: 'Case-sensitive ARN matching' },
  ArnEqualsIfExists: { description: 'ARN matching; true if key is absent' },
  'ForAllValues:ArnEquals': { description: 'All values must match at least one policy ARN' },
  'ForAnyValue:ArnEquals': { description: 'At least one value must match a policy ARN' },
  ArnLike: { description: 'Case-sensitive ARN matching with wildcard support (* and ?)' },
  ArnLikeIfExists: { description: 'ARN wildcard matching; true if key is absent' },
  'ForAllValues:ArnLike': { description: 'All values must match at least one policy ARN pattern' },
  'ForAnyValue:ArnLike': { description: 'At least one value must match a policy ARN pattern' },
  ArnNotEquals: { description: 'Negated case-sensitive ARN matching' },
  ArnNotEqualsIfExists: { description: 'Negated ARN matching; true if key is absent' },
  'ForAllValues:ArnNotEquals': { description: 'None of the values can match any policy ARN' },
  'ForAnyValue:ArnNotEquals': { description: 'At least one value must not match any policy ARN' },
  ArnNotLike: { description: 'Negated case-sensitive ARN matching with wildcard support' },
  ArnNotLikeIfExists: { description: 'Negated ARN wildcard matching; true if key is absent' },
  'ForAllValues:ArnNotLike': { description: 'None of the values can match any policy ARN pattern' },
  'ForAnyValue:ArnNotLike': { description: 'At least one value must not match any policy ARN pattern' },

  // Null
  Null: { description: 'Checks whether a condition key is present (true if absent, false if present)' },
} as const;
