export const partitions = {
  aws: {
    name: 'AWS Commercial Regions',
    regions: [
      { id: 'us-east-1', name: 'US East (N. Virginia)' },
      { id: 'us-east-2', name: 'US East (Ohio)' },
      { id: 'us-west-1', name: 'US West (N. California)' },
      { id: 'us-west-2', name: 'US West (Oregon)' },
      { id: 'af-south-1', name: 'Africa (Cape Town)' },
      { id: 'ap-east-1', name: 'Asia Pacific (Hong Kong)' },
      { id: 'ap-south-1', name: 'Asia Pacific (Mumbai)' },
      { id: 'ap-south-2', name: 'Asia Pacific (Hyderabad)' },
      { id: 'ap-southeast-1', name: 'Asia Pacific (Singapore)' },
      { id: 'ap-southeast-2', name: 'Asia Pacific (Sydney)' },
      { id: 'ap-southeast-3', name: 'Asia Pacific (Jakarta)' },
      { id: 'ap-southeast-4', name: 'Asia Pacific (Melbourne)' },
      { id: 'ap-southeast-5', name: 'Asia Pacific (Malaysia)' },
      { id: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)' },
      { id: 'ap-northeast-2', name: 'Asia Pacific (Seoul)' },
      { id: 'ap-northeast-3', name: 'Asia Pacific (Osaka)' },
      { id: 'ca-central-1', name: 'Canada (Central)' },
      { id: 'ca-west-1', name: 'Canada West (Calgary)' },
      { id: 'eu-central-1', name: 'Europe (Frankfurt)' },
      { id: 'eu-central-2', name: 'Europe (Zurich)' },
      { id: 'eu-west-1', name: 'Europe (Ireland)' },
      { id: 'eu-west-2', name: 'Europe (London)' },
      { id: 'eu-west-3', name: 'Europe (Paris)' },
      { id: 'eu-south-1', name: 'Europe (Milan)' },
      { id: 'eu-south-2', name: 'Europe (Spain)' },
      { id: 'eu-north-1', name: 'Europe (Stockholm)' },
      { id: 'il-central-1', name: 'Israel (Tel Aviv)' },
      { id: 'me-south-1', name: 'Middle East (Bahrain)' },
      { id: 'me-central-1', name: 'Middle East (UAE)' },
      { id: 'sa-east-1', name: 'South America (São Paulo)' },
    ],
  },
  'aws-us-gov': {
    name: 'AWS GovCloud (US) Regions',
    regions: [
      { id: 'us-gov-west-1', name: 'AWS GovCloud (US-West)' },
      { id: 'us-gov-east-1', name: 'AWS GovCloud (US-East)' },
    ],
  },
  'aws-cn': {
    name: 'AWS China Regions',
    regions: [
      { id: 'cn-north-1', name: 'China (Beijing)' },
      { id: 'cn-northwest-1', name: 'China (Ningxia)' },
    ],
  },
} as const;
