---
includes:
  - s3:ResourceAccount
  - s3:TlsVersion
excludes:
  - ec2:ResourceTag/${TagKey}
---
Resources:
  MyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"
            Condition:
              StringEquals:
                $0
